// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9_VfK7wisVFXsWc3Pf3V-GjOLzjNQM9c',
    appId: '1:1047873916574:web:3e49b2007d8c0a9e12f58f',
    messagingSenderId: '1047873916574',
    projectId: 'promotions-app-cdae2',
    authDomain: 'promotions-app-cdae2.firebaseapp.com',
    databaseURL: 'https://promotions-app-cdae2-default-rtdb.firebaseio.com',
    storageBucket: 'promotions-app-cdae2.appspot.com',
    measurementId: 'G-1CBCLGT3EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_YddU4zsnbksJMsWo4nPfRt3vMRhmWjk',
    appId: '1:1047873916574:android:0376b23d9516bb7212f58f',
    messagingSenderId: '1047873916574',
    projectId: 'promotions-app-cdae2',
    databaseURL: 'https://promotions-app-cdae2-default-rtdb.firebaseio.com',
    storageBucket: 'promotions-app-cdae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQIj0e3697x0bQmPdKmJdmdl-3Zm7--EQ',
    appId: '1:1047873916574:ios:8941edb7ad97d9bc12f58f',
    messagingSenderId: '1047873916574',
    projectId: 'promotions-app-cdae2',
    databaseURL: 'https://promotions-app-cdae2-default-rtdb.firebaseio.com',
    storageBucket: 'promotions-app-cdae2.appspot.com',
    iosBundleId: 'com.example.reidaspromocoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQIj0e3697x0bQmPdKmJdmdl-3Zm7--EQ',
    appId: '1:1047873916574:ios:8941edb7ad97d9bc12f58f',
    messagingSenderId: '1047873916574',
    projectId: 'promotions-app-cdae2',
    databaseURL: 'https://promotions-app-cdae2-default-rtdb.firebaseio.com',
    storageBucket: 'promotions-app-cdae2.appspot.com',
    iosBundleId: 'com.example.reidaspromocoes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9_VfK7wisVFXsWc3Pf3V-GjOLzjNQM9c',
    appId: '1:1047873916574:web:c29d292f616232e112f58f',
    messagingSenderId: '1047873916574',
    projectId: 'promotions-app-cdae2',
    authDomain: 'promotions-app-cdae2.firebaseapp.com',
    databaseURL: 'https://promotions-app-cdae2-default-rtdb.firebaseio.com',
    storageBucket: 'promotions-app-cdae2.appspot.com',
    measurementId: 'G-6XSZW3Y91B',
  );

}